%verify psnr_of_frame function

function []=verify_psnr_of_frame();

%test_image = double(imread('cameraman.tif'))/255;
test_image = yuv_read_one_frame('flowergarden_short_cif.yuv',1,352,288);

% load uniformly distributed noise
% generated by: 
% noise = rand(size(test_image))-0.5;
% also loads correct values test_psnr
load mse_psnr_verification_noise;

% open new figure
figure;
set(gcf,'position',[100 500 1200 300]);
your_psnr = NaN * zeros(1,4);
for l=1:4
  noisy_image = test_image + (l-1)*0.1*noise;
  your_psnr(l) =  psnr_of_frame(test_image,noisy_image);
  eval(['subplot(14' num2str(l) ')']);
  imshow(noisy_image)
  title(['PSNR: ' num2str(test_psnr(l)) ' dB'])
  xlabel(['your PSNR: ' num2str(your_psnr(l)) ' dB'])
end
% wen don't check for equality to take into account rounding operations
if (any(abs(your_psnr-test_psnr)>10e-12))
  error('wrong PSNR values! Check function! Is output in dB?')
end
disp('function psnr_of_frame is ok!')

if(0)
  % used to save correct/expected values
  test_mse = your_mse;
  save mse_psnr_verification_noise noise test_mse test_psnr;
end
